version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      spring-boot:
        patterns:
          - "org.springframework.boot:*"
      security-patches:
        applies-to: security-updates
        patterns:
          - "*"
