server.port=8001

spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:1234}
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/flight_reservation}

spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health,info,metrics


